name: Nightly Build

on:
  schedule:
    - cron: '0 3 * * 1' # 03:00 UTC every Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print timestamp
        run: echo "Current UTC time: $(date -u +"%Y-%m-%d %H:%M")"
