name: Nightly Build

on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print timestamp
        run: |
          echo "Current UTC time: $(date -u '+%Y-%m-%d %H:%M')"
